### ISSUE TITLE
Deploy on k8s

### ISSUE THREAD

**Issue by ruipoliveira** [Blueswen/fastapi-observability#1]
Hello all!
I will implement "fastapi observability" on kubernetes. Did you think of something for driver loki? 

```
x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},d{3}) (?P<message>(?s:.*))$$'
 
```
Regards
