### ISSUE TITLE
How to filter metrics when sending trace to tempo?

### ISSUE THREAD

**Issue by npuichigo** [Blueswen/fastapi-observability#14]
I think it's quite noisy to have a bundle of `/metrics` traces in tempo/grafana. Any way to avoid sending that?

**Comment by blueswen** [comment]
OpenTelemetry Collector's [Tail Sampling Processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor) can remove or keep the given ratio whole span by condition. Following is an OpenTelemetry Collector config sample:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http: 

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

processors:
  batch:
  tail_sampling:
    decision_wait: 10s
    num_traces: 100
    expected_new_traces_per_sec: 10
    policies:
      [
        {
          name: keep-all-policy,
          type: always_sample
        },
        {
            name: remove-health-and-metrics-policy,
            type: string_attribute,
            string_attribute: {key: http.url, values: [\/health, \/metrics], enabled_regex_matching: true, invert_match: true}
         }
      ]

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling, batch]
      exporters: [otlp]
```

Try this config with my workshop [lab](https://github.com/blueswen/observability-workshop-101/tree/main/lab-4).
