### ISSUE TITLE
Not Found loki config in `/etc`

### ISSUE THREAD

**Issue by z0z0r4** [Blueswen/fastapi-observability#18]
https://github.com/blueswen/fastapi-observability/tree/main/etc

**Comment by PaulineMauryL** [comment]
Hi, thanks @blueswen for the great and complete example!
I have the same issue, the file is referenced in docker-compose.yaml but then not in the repo.

```
services:
  loki:
    image: grafana/loki:3.0.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
```

Would you have an example ?
