### ISSUE TITLE
Grafana 9.5 support

### ISSUE THREAD

**Issue by kamikaze** [Blueswen/fastapi-observability#4]
Is dashboard compatible with Grafana 9.5?

**Comment by blueswen** [comment]
The dashboard is working on Grafana 9.5.2 on my Mac when login with admin account as follows:

<img width="1916" alt="Dashboard" src="https://github.com/blueswen/fastapi-observability/assets/1564148/130577ac-20b8-41ae-880e-412c5ec271b6">

But it has permission issues when using an anonymous user and you may get Unauthorized error. You can enable the Grafana login form in `docker-compose.yaml` as follows and login with admin account:

```
  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      # GF_AUTH_DISABLE_LOGIN_FORM: "true" <=== mark this to enable login form
```

This issue is related to Grafana itself, but I can't find a document or changelog that mentions this change. This issue may be fixed in the new version later.
